syntax = "proto3";

service PubSubService {
    rpc Subscribe(SubscribeRequest) returns (stream Noticia);
    rpc Publish(PublishRequest) returns (PublishResponse);
    rpc Unsubscribe(UnsubscribeRequest) returns (UnsubscribeResponse);
}

message SubscribeRequest {
    string subscriber_id = 1;
    string topic = 2;
}

message Noticia {
    string topic = 1;
    string titulo = 2;
    string conteudo = 3;
}

message PublishRequest {
    string topic = 1;
    string titulo = 2;
    string conteudo = 3;
}

message PublishResponse {
    bool success = 1;
}

message UnsubscribeRequest {
    string subscriber_id = 1;
    string topic = 2;
}

message UnsubscribeResponse {
    bool success = 1;
}