# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pubsub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\"8\n\x10SubscribeRequest\x12\x15\n\rsubscriber_id\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\":\n\x07Noticia\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x03 \x01(\t\"A\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x03 \x01(\t\"\"\n\x0fPublishResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\":\n\x12UnsubscribeRequest\x12\x15\n\rsubscriber_id\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\"&\n\x13UnsubscribeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa3\x01\n\rPubSubService\x12*\n\tSubscribe\x12\x11.SubscribeRequest\x1a\x08.Noticia0\x01\x12,\n\x07Publish\x12\x0f.PublishRequest\x1a\x10.PublishResponse\x12\x38\n\x0bUnsubscribe\x12\x13.UnsubscribeRequest\x1a\x14.UnsubscribeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=16
  _globals['_SUBSCRIBEREQUEST']._serialized_end=72
  _globals['_NOTICIA']._serialized_start=74
  _globals['_NOTICIA']._serialized_end=132
  _globals['_PUBLISHREQUEST']._serialized_start=134
  _globals['_PUBLISHREQUEST']._serialized_end=199
  _globals['_PUBLISHRESPONSE']._serialized_start=201
  _globals['_PUBLISHRESPONSE']._serialized_end=235
  _globals['_UNSUBSCRIBEREQUEST']._serialized_start=237
  _globals['_UNSUBSCRIBEREQUEST']._serialized_end=295
  _globals['_UNSUBSCRIBERESPONSE']._serialized_start=297
  _globals['_UNSUBSCRIBERESPONSE']._serialized_end=335
  _globals['_PUBSUBSERVICE']._serialized_start=338
  _globals['_PUBSUBSERVICE']._serialized_end=501
# @@protoc_insertion_point(module_scope)
